---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Haha!" 
      
  - name: Create file
    file:
      path: /tmp/test.txt
      owner: root
      group: root
      mode: '777'
