---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Haha!" 
      
  - name: Create file
    file:
      path: /tmp/test.txt
      state: touch
      
  - name: Hello var
    debug:
      msg: "{{ test_var | upper}}" 
      
  - name: Hello no var
    debug:
      msg: "{{ test_no_var | default(88) }}" 
